canteen/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name='home'),
    path('about_us/', views.AboutUsPage.as_view(), name='about_us'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('loggedin/', views.LoggedInPage.as_view(), name='loggedin'),
    path('menu/', include('menu.urls', namespace='menu')),
    path('food_cart/', include('food_cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_cart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from . import views

app_name='food_cart'

urlpatterns=[

	path('',views.cart_detail,name='cart_detail'),
	path('add/<int:product_id>',views.cart_add,name="cart_add"),
	path('remove/<int:product_id>',views.cart_remove,name="cart_remove"),
	#path('order_complete/',views.order_complete,name='order_complete'),
	path('clearcart/',views.clearcart,name="clearcart"),
]

menu/urls.py
from django.contrib import admin
from . import views
from django.urls import path,include
from django.views.generic.base import TemplateView

app_name='menu'


urlpatterns = [
	path('item_list/',views.item_list,name='item_list'),
	path('<str:category_slug>/',views.item_list,name="items_list_by_category"),
 	path('<int:id>/<slug:slug>/',views.item_detail,name='item_detail'),
]

food_cart/models.py
from django.db import models

# Create your models here.

food_cart/forms.py
from django import forms
from menu.models import Item

PRODUCT_QUANTITY_CHOICES=[(i, str(i)) for i in range(1,11)]

class CartAddProductForm(forms.Form):
 	quantity=forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
 	update=forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

food_cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from menu.models import Item
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(item=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('food_cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Item, id=product_id)
    cart.remove(product)
    return redirect('food_cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})

    return render(request, 'food_cart/detail.html', {'cart': cart})
"""
def order_complete(request):
    cart = Cart(request)
    cart.clear()
    return render(request,'food_cart/order_complete.html')
"""
def clearcart(request):
    cart=Cart(request)
    cart.clear()
    return redirect('menu:item_list')

food_cart/templates/food_cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}

    Your Food cart
}
{% endblock %}

{% block content %}
<div class="container">
    <h1 id="urfood">Order Reciept</h1>
    <label for="name">Name :</label>
    <input id="name" type="text" name="name">
    <br>
    <label for="contact">Contact No. :</label>
    <input id="contact" type="text" name="contact">
    <input id="roomin" type="text" name="room">
    <label id="room" for="room">Room No. :</label>
    <table class="cart table table-bordered table-hover">
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with item1=item.product %}
            <tr>
                <td>{{ item1.name }}  {{ item1.quantity }}</td>
                <td>
                   {% with item2=item.update_quantity_form %}
                    <form action="{% url 'cart:cart_add' item1.id %}" method="post">
                        {{ item2.quantity}}
                        <input type="submit" class="btn btn-outline-dark btn-sm" value="Update">
                        {% csrf_token %}
                    </form>
                    {% endwith %}
                </td>

                <td><a id="remove" href="{% url 'cart:cart_remove' item1.id %}">Remove</a></td>
                <td class="num">₹{{ item.price }}</td>
                <td class="num">₹{{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="3"></td>
            <td class="num">₹{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'cart:clearcart' %}" class="btn btn-danger">Clear Cart</a>
        <a href="{% url 'menu:item_list' %}" class="btn btn-primary">Add More Items</a>
        <button onclick="window.print()" class="btn btn-success">Print Reciept</button>

    </p>
</div>
{% endblock %}