canteen/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name='home'),
    path('about_us/', views.AboutUsPage.as_view(), name='about_us'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('loggedin/', views.LoggedInPage.as_view(), name='loggedin'),
    path('menu/', include('menu.urls', namespace='menu')),
    path('food_cart/', include('food_cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_cart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from . import views

app_name='food_cart'

urlpatterns=[

	path('',views.cart_detail,name='cart_detail'),
	path('add/<int:product_id>',views.cart_add,name="cart_add"),
	path('remove/<int:product_id>',views.cart_remove,name="cart_remove"),
	#path('order_complete/',views.order_complete,name='order_complete'),
	path('clearcart/',views.clearcart,name="clearcart"),
]

menu/urls.py
from django.contrib import admin
from . import views
from django.urls import path,include
from django.views.generic.base import TemplateView

app_name='menu'


urlpatterns = [
	path('item_list/',views.item_list,name='item_list'),
	path('<str:category_slug>/',views.item_list,name="items_list_by_category"),
 	path('<int:id>/<slug:slug>/',views.item_detail,name='item_detail'),
]

menu/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, unique=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)
    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_urls(self):
    	return reverse('menu:item_list_by_category',args=[self.slug] )

    def save(self,**kwargs):
        super(Category, self).save(**kwargs)

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True, unique=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    image = models.ImageField(upload_to='products', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_urls(self):
    	return reverse('menu:views.item_detail',args=[self.id,self.slug] )

    def save(self, **kwargs):
        super(Item, self).save(**kwargs)

menu/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Category, Item
from food_cart.forms import CartAddProductForm
from food_cart.cart import Cart
from django.contrib.auth.decorators import login_required
# Create your views here
@login_required(login_url='main_home')
def item_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    items = Item.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        items = Item.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'items': items
    }
    return render(request, 'menu/list.html', context)

@login_required(login_url='main_home')
def item_detail(request, id, slug):
    q=0
    item = get_object_or_404(Item, id=id, slug=slug, available=True)
    cart = Cart(request)
    for i in cart:
        if i['product']==item:
            q=i['quantity']
            break
    cart_product_form=CartAddProductForm(initial={'quantity':q})
    return render(request, 'menu/detail.html', {'item': item,'cart_product_form':cart_product_form})

menu/templates/menu/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {{ item.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img style="width: 250px" src="{% if item.image %}{{ item.image.url }}{% else %}{% static 'shop/no_image.png' %}{% endif %} " height="300">
        <h1>{{ item.name }}</h1>
        <h2><a href="{{ item.category.get_absolute_url }}">{{ item.category }}</a></h2>
        <p class="price">₹{{ item.price }}</p>
        <form class="price" action="{% url 'food_cart:cart_add' item.id %}" method="post">

            {{ cart_product_form }}

            {% csrf_token %}
            <input type="submit" style="background-color: white" value="Add to cart">
        </form>
    </div>
{% endblock %}

menu/templates/menu/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Items{% endif %}
{% endblock %}

{% block content %}
{% if user.is_authenticated and user.is_employee %}
    <div id="sidebar">
        <h3 id="heading">Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a id="cat" href="{% url 'menu:item_list' %}">All</a>
            </li>
        {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
              <a id="cat" href="{% url 'menu:items_list_by_category' category_slug=c.slug %}">{{ c.name }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Items{% endif %}</h1>

        {% for item in items %}
            <div class="item">
                <a href="{% url 'menu:item_detail' id=item.id slug=item.slug %}">
                    <img src="{% if item.image %}{{ item.image.url }}{% else %}{% static 'shop/no_image.png' %}{% endif %}" height="200">
                </a><br>
                <a id="item" href="{% url 'menu:item_detail' id=item.id slug=item.slug %}">{{ item.name }}</a><br>
                <p id="item">₹{{ item.price }}</p>
            </div>
        {% endfor %}
    </div>
{% else %}
<div id="sidebar">
    <h3 id="heading">Categories</h3>
    <ul>
        <li {% if not category %}class="selected"{% endif %}>
            <a id="cat" href="{% url 'menu:item_list' %}">All</a>
        </li>
    {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a id="cat" href="{% url 'menu:items_list_by_category' category_slug=c.slug %}">{{ c.name }}</a>
        </li>
    {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Items{% endif %}</h1>

    {% for item in items %}
        <div class="item">
            <img src="{% if item.image %}{{ item.image.url }}{% else %}{% static 'shop/no_image.png' %}{% endif %}" height="200">
            <br>
            {{ item.name }}
            <br>
            ₹{{ item.price }}
        </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}