canteen/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name='home'),
    path('about_us/', views.AboutUsPage.as_view(), name='about_us'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('loggedin/', views.LoggedInPage.as_view(), name='loggedin'),
    path('menu/', include('menu.urls', namespace='menu')),
    path('food_cart/', include('food_cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.contrib import admin
from . import views
from django.urls import path,include
from django.views.generic.base import TemplateView

app_name='menu'


urlpatterns = [
	path('item_list/',views.item_list,name='item_list'),
	path('<str:category_slug>/',views.item_list,name="items_list_by_category"),
 	path('<int:id>/<slug:slug>/',views.item_detail,name='item_detail'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('<pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('list', views.OrderListView.as_view(), name='order_list'),
    path('update/<pk>/', views.OrderUpdateView.as_view(), name='order_update'),
    path('delete/<pk>/', views.OrderDeleteView.as_view(), name='order_delete'),
]

order/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Message(models.Model):
    name = models.CharField(max_length=50)
    contact_no = models.CharField(max_length=10)
    room_no = models.CharField(max_length=5)
    order = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('order:order_detail', kwargs={'pk':self.pk})

order/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView)
from .models import Message
from django.urls import reverse_lazy
# Create your views here.

class OrderCreateView(CreateView):
    model = Message
    fields = ['name', 'contact_no', 'room_no', 'order']

class OrderDetailView(DetailView):
    context_object_name = 'order_detail'
    model = Message
    template_name = 'order/order_detail.html'

class OrderListView(ListView):
    model = Message

class OrderUpdateView(UpdateView):
    fields = ['name', 'contact_no', 'room_no', 'order']
    model = Message

class OrderDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('home')

order/templates/order/message_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div id="ques" class="container">
  {% if user.is_customer %}
    <h1> Are you sure you want to cancel the order ??</h1>
    <form method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger" value="Yes">
      <a href="{% url 'order:order_detail' pk=message.pk %}" class="btn btn-success">No</a>
    </form>
  {% else %}
    <h1>Order Placed Successfully..!!</h1>
    <form method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-success" value="Back to Home">
    </form>
  {% endif %}
</div>
{% endblock %}

order/templates/order/message_form.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}
{% block content %}
<h1 id="Eod">Enter order details</h1>
<div class="order_form container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success" value="Order">
  </form>
</div>
{% endblock %}

order/templates/order/message_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="list container">
  <h1>Pending Orders</h1>
  {% for m in message_list %}
    <h2 id="orders"><a href="{{m.id}}">Order Number {{m.id}}</a></h2>
  {% empty %}
    <h2>No pending orders</h2>
  {% endfor %}
</div>
{% endblock %}

order/templates/order/order_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
  {% if user.is_customer %}
  <h1 id="urorder"> Your Order </h1>
  {% else %}
  <h1 id="urorder"> Order Details </h1>
  {% endif %}
  <div class="detail">
    <p>Name: {{order_detail.name}}</p>
    <p>Contact No.: {{order_detail.contact_no}}</p>
    <p>Room No.: {{order_detail.room_no}}</p>
    <p>Order: {{order_detail.order}}</p>
  </div>
  {% if user.is_customer %}
  <a href="{% url 'order:order_update' pk=order_detail.pk %}" class="but btn btn-warning">Change Order</a>
  <a href="{% url 'order:order_delete' pk=order_detail.pk %}" class="but btn btn-danger">Cancel Order</a>
  <a href="{% url 'home' %}" class="but btn btn-success">Place Order</a>
  {% else %}
  <a href="{% url 'order:order_delete' pk=order_detail.pk %}" class="btn btn-success">Order Completed</a>
  <a href="{% url 'menu:item_list' %}" target="_blank" class="btn btn-primary">Generate Reciept</a>
  {% endif %}
</div>
{% endblock %}