accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('customer_signup/', views.CustomerSignUpView.as_view(), name='customer_signup'),
    path('employee_signup/', views.EmployeeSignUpView.as_view(), name='employee_signup'),
]

canteen/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(), name='home'),
    path('about_us/', views.AboutUsPage.as_view(), name='about_us'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('loggedin/', views.LoggedInPage.as_view(), name='loggedin'),
    path('menu/', include('menu.urls', namespace='menu')),
    path('food_cart/', include('food_cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.contrib import admin
from . import views
from django.urls import path,include
from django.views.generic.base import TemplateView

app_name='menu'


urlpatterns = [
	path('item_list/',views.item_list,name='item_list'),
	path('<str:category_slug>/',views.item_list,name="items_list_by_category"),
 	path('<int:id>/<slug:slug>/',views.item_detail,name='item_detail'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('<pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('list', views.OrderListView.as_view(), name='order_list'),
    path('update/<pk>/', views.OrderUpdateView.as_view(), name='order_update'),
    path('delete/<pk>/', views.OrderDeleteView.as_view(), name='order_delete'),
]

templates/about_us.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="aboutus container">
    <h1 id="des">Description of the project</h1>
    <p>The Website aims to ease the process of ordering food from canteens in the college.</p>
    <p>The website uses Django sessions and user defined context pre-processor for the ‘Cart’ Application to save all the items in the current session and gets deleted after the user logs out.</p>
    <p>The Django project uses ImageField Attribute in the ‘Item’ model, which requires the pillow library which needs to be installed(using pip install pillow).</p>
    <p>Any user who is not logged in and tries to manually edit the URL in browser’s tab is redirected to the homepage.</p>
    <p>The website has the following Applications:</p>
    <ul>
      <li>Accounts (For login and signup)</li>
      <li>Menu (For the list of items available)</li>
      <li>Food Cart (For the order functionality)</li>
    </ul>
    <p>The tables inside the database are:</p>
    <ul>
      <li>Users</li>
      <li>Categories</li>
      <li>Items</li>
    </ul>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/order.css' %}">
    <link rel="stylesheet" href="{% static 'css/employee.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light mynav" role="navigation" id="navbar">
      <div class="container-fluid">
        <a class="navbar-brand mynav" href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" width="150" height="60" class="d-inline-block align-top" loading="lazy"></a>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated and user.is_customer%}
          <li class="nav-item"> <a class="nav-link" href="{% url 'menu:item_list' %}">Menu</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'order:order_create' %}">Order</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a> </li>
          {% elif user.is_authenticated and user.is_employee %}
          <li class="nav-item"> <a class="nav-link" href="{% url 'order:order_list' %}">Order Requests</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'menu:item_list' %}">Order Now</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a> </li>
          {% else %}
          <li class="nav-item"> <a class="nav-link" href="{% url 'home' %}">Home</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'about_us' %}">About Us</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:login' %}">Login</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:customer_signup' %}">Customer Sign Up</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'accounts:employee_signup' %}">Employee Sign Up</a> </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'admin:index' %}">Admin</a> </li>
          {% endif %}
        </ul>
      </div>
    </nav>
      {% block content %}

      {% endblock %}
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to DY Patil's Canteen..!!</h1>
  </div>
  <img src="{% static 'images/food1.jpg' %}" height="200" alt=""> <img src="{% static 'images/food2.jpg' %}" height="200" alt=""> <img src="{% static 'images/food3.jpeg' %}" width="350" height="200" alt="">
</div>
{% endblock %}

templates/loggedin.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            {% if user.is_authenticated and user.is_customer %}
                <h1>Welcome {{user.first_name}} {{user.last_name}} to DY Patil's Canteen</h1>
                <hr>
                <a href="{% url 'menu:item_list' %}" class="btn btn-primary">Today's Menu</a>
                <a href="{% url 'order:order_create' %}" class="btn  btn-secondary">Order Now</a>
            {% else %}
                <h1>Welcome {{user.username}}. It's a brand new day. You are now logged in..!!</h1>
                <hr>
                <a href="{% url 'order:order_list' %}" class="btn  btn-primary">Order Requests</a>
                <a href="{% url 'menu:item_list' %}" class="btn  btn-primary">Place Order</a>
            {% endif %}
        </div>
    </div>    
{% endblock %}